/**
 * Docker Engine API The Engine API is an HTTP API served by Docker Engine. It is the API the Docker
 * client uses to communicate with the Engine, so everything the Docker client can do can be done
 * with the API. Most of the client's commands map directly to API endpoints (e.g. `docker ps` is
 * `GET /containers/json`). The notable exception is running containers, which consists of several
 * API calls. # Errors The API uses standard HTTP status codes to indicate the success or failure of
 * the API call. The body of the response will be JSON in the following format: ``` { \"message\":
 * \"page not found\" } ``` # Versioning The API is usually changed in each release, so API calls
 * are versioned to ensure that clients don't break. To lock to a specific version of the API, you
 * prefix the URL with its version, for example, call `/v1.30/info` to use the v1.30 version of the
 * `/info` endpoint. If the API version specified in the URL is not supported by the daemon, a HTTP
 * `400 Bad Request` error message is returned. If you omit the version-prefix, the current version
 * of the API (v1.43) is used. For example, calling `/info` is the same as calling `/v1.43/info`.
 * Using the API without a version-prefix is deprecated and will be removed in a future release.
 * Engine releases in the near future should support this version of the API, so your client will
 * continue to work even if it is talking to a newer Engine. The API uses an open schema model,
 * which means server may add extra properties to responses. Likewise, the server will ignore any
 * extra query parameters and request body properties. When you write clients, you need to ignore
 * additional properties in responses to ensure they do not break when talking to newer daemons. #
 * Authentication Authentication for registries is handled client side. The client has to send
 * authentication details to various endpoints that need to communicate with registries, such as
 * `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a [base64url
 * encoded](https://tools.ietf.org/html/rfc4648#section-5) (JSON) string with the following
 * structure: ``` { \"username\": \"string\", \"password\": \"string\", \"email\": \"string\",
 * \"serveraddress\": \"string\" } ``` The `serveraddress` is a domain/IP without a protocol.
 * Throughout this structure, double quotes are required. If you have already got an identity token
 * from the [`/auth` endpoint](#operation/SystemAuth), you can just pass this instead of
 * credentials: ``` { \"identitytoken\": \"9cbaf023786cd7...\" } ```
 *
 * The version of the OpenAPI document: 1.43
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.ErrorResponse
import org.openapitools.client.model.Volume
import org.openapitools.client.model.VolumeCreateOptions
import org.openapitools.client.model.VolumeListResponse
import org.openapitools.client.model.VolumePruneResponse
import org.openapitools.client.model.VolumeUpdateRequest
import org.openapitools.client.core.JsonSupport.{*, given}
import sttp.client4.*
import sttp.model.Method

object VolumeApi:
  def apply(baseUrl: String = "http://localhost/v1.43") = new VolumeApi(baseUrl)

end VolumeApi

class VolumeApi(baseUrl: String):

  /**
   * Expected answers: code 201 : Volume (The volume was created successfully) code 500 :
   * ErrorResponse (Server error)
   *
   * @param volumeConfig
   *   Volume configuration
   */
  def volumeCreate(volumeConfig: VolumeCreateOptions)
      : Request[Either[ResponseException[String, Exception], Volume]] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/volumes/create")
      .contentType("application/json")
      .body(volumeConfig)
      .response(asJson[Volume])

  /**
   * Instruct the driver to remove the volume.
   *
   * Expected answers: code 204 : (The volume was removed) code 404 : ErrorResponse (No such volume
   * or volume driver) code 409 : ErrorResponse (Volume is in use and cannot be removed) code 500 :
   * ErrorResponse (Server error)
   *
   * @param name
   *   Volume name or ID
   * @param force
   *   Force the removal of the volume
   */
  def volumeDelete(name: String, force: Option[Boolean] = None)
      : Request[Either[ResponseException[String, Exception], Unit]] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/volumes/${name}?force=${force}")
      .contentType("application/json")
      .response(asString.mapWithMetadata(ResponseAs.deserializeRightWithError(_ => Right(()))))

  /**
   * Expected answers: code 200 : Volume (No error) code 404 : ErrorResponse (No such volume) code
   * 500 : ErrorResponse (Server error)
   *
   * @param name
   *   Volume name or ID
   */
  def volumeInspect(name: String): Request[Either[ResponseException[String, Exception], Volume]] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/volumes/${name}")
      .contentType("application/json")
      .response(asJson[Volume])

  /**
   * Expected answers: code 200 : VolumeListResponse (Summary volume data that matches the query)
   * code 500 : ErrorResponse (Server error)
   *
   * @param filters
   *   JSON encoded value of the filters (a `map[string][]string`) to process on the volumes list.
   *   Available filters: - `dangling=<boolean>` When set to `true` (or `1`), returns all volumes
   *   that are not in use by a container. When set to `false` (or `0`), only volumes that are in
   *   use by one or more containers are returned. - `driver=<volume-driver-name>` Matches volumes
   *   based on their driver. - `label=<key>` or `label=<key>:<value>` Matches volumes based on the
   *   presence of a `label` alone or a `label` and a value. - `name=<volume-name>` Matches all or
   *   part of a volume name.
   */
  def volumeList(filters: Option[String] = None)
      : Request[Either[ResponseException[String, Exception], VolumeListResponse]] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/volumes?filters=${filters}")
      .contentType("application/json")
      .response(asJson[VolumeListResponse])

  /**
   * Expected answers: code 200 : VolumePruneResponse (No error) code 500 : ErrorResponse (Server
   * error)
   *
   * @param filters
   *   Filters to process on the prune list, encoded as JSON (a `map[string][]string`). Available
   *   filters: - `label` (`label=<key>`, `label=<key>=<value>`, `label!=<key>`, or
   *   `label!=<key>=<value>`) Prune volumes with (or without, in case `label!=...` is used) the
   *   specified labels. - `all` (`all=true`) - Consider all (local) volumes for pruning and not
   *   just anonymous volumes.
   */
  def volumePrune(filters: Option[String] = None)
      : Request[Either[ResponseException[String, Exception], VolumePruneResponse]] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/volumes/prune?filters=${filters}")
      .contentType("application/json")
      .response(asJson[VolumePruneResponse])

  /**
   * Expected answers: code 200 : (no error) code 400 : ErrorResponse (bad parameter) code 404 :
   * ErrorResponse (no such volume) code 500 : ErrorResponse (server error) code 503 : ErrorResponse
   * (node is not part of a swarm)
   *
   * @param name
   *   The name or ID of the volume
   * @param version
   *   The version number of the volume being updated. This is required to avoid conflicting writes.
   *   Found in the volume's `ClusterVolume` field.
   * @param body
   *   The spec of the volume to update. Currently, only Availability may change. All other fields
   *   must remain unchanged.
   */
  def volumeUpdate(
      name: String,
      version: Long,
      body: Option[VolumeUpdateRequest] = None,
    ): Request[Either[ResponseException[String, Exception], Unit]] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/volumes/${name}?version=${version}")
      .contentType("application/json")
      .body(body)
      .response(asString.mapWithMetadata(ResponseAs.deserializeRightWithError(_ => Right(()))))

end VolumeApi
